# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from redstone.core.v1 import core_pb2 as redstone_dot_core_dot_v1_dot_core__pb2


class RegisterServiceStub:
    """---------------------------------------------------------------- register

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Bind = channel.unary_unary(
                '/redstone.core.v1.RegisterService/Bind',
                request_serializer=redstone_dot_core_dot_v1_dot_core__pb2.BindRequest.SerializeToString,
                response_deserializer=redstone_dot_core_dot_v1_dot_core__pb2.BindResponse.FromString,
                _registered_method=True)
        self.ListInstances = channel.unary_unary(
                '/redstone.core.v1.RegisterService/ListInstances',
                request_serializer=redstone_dot_core_dot_v1_dot_core__pb2.ListInstancesRequest.SerializeToString,
                response_deserializer=redstone_dot_core_dot_v1_dot_core__pb2.ListInstancesResponse.FromString,
                _registered_method=True)
        self.GetGraph = channel.unary_unary(
                '/redstone.core.v1.RegisterService/GetGraph',
                request_serializer=redstone_dot_core_dot_v1_dot_core__pb2.GetGraphRequest.SerializeToString,
                response_deserializer=redstone_dot_core_dot_v1_dot_core__pb2.GetGraphResponse.FromString,
                _registered_method=True)


class RegisterServiceServicer:
    """---------------------------------------------------------------- register

    """

    def Bind(self, request, context):
        """GET /bind?capability=&level=[&name=][&label.k=v][&consumer=][&as=]
        200 -> BindResponse    409 -> BindRefusal    400 -> bad request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInstances(self, request, context):
        """GET /instances
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraph(self, request, context):
        """GET /graph
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegisterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Bind': grpc.unary_unary_rpc_method_handler(
                    servicer.Bind,
                    request_deserializer=redstone_dot_core_dot_v1_dot_core__pb2.BindRequest.FromString,
                    response_serializer=redstone_dot_core_dot_v1_dot_core__pb2.BindResponse.SerializeToString,
            ),
            'ListInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstances,
                    request_deserializer=redstone_dot_core_dot_v1_dot_core__pb2.ListInstancesRequest.FromString,
                    response_serializer=redstone_dot_core_dot_v1_dot_core__pb2.ListInstancesResponse.SerializeToString,
            ),
            'GetGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraph,
                    request_deserializer=redstone_dot_core_dot_v1_dot_core__pb2.GetGraphRequest.FromString,
                    response_serializer=redstone_dot_core_dot_v1_dot_core__pb2.GetGraphResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'redstone.core.v1.RegisterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('redstone.core.v1.RegisterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegisterService:
    """---------------------------------------------------------------- register

    """

    @staticmethod
    def Bind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/redstone.core.v1.RegisterService/Bind',
            redstone_dot_core_dot_v1_dot_core__pb2.BindRequest.SerializeToString,
            redstone_dot_core_dot_v1_dot_core__pb2.BindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/redstone.core.v1.RegisterService/ListInstances',
            redstone_dot_core_dot_v1_dot_core__pb2.ListInstancesRequest.SerializeToString,
            redstone_dot_core_dot_v1_dot_core__pb2.ListInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/redstone.core.v1.RegisterService/GetGraph',
            redstone_dot_core_dot_v1_dot_core__pb2.GetGraphRequest.SerializeToString,
            redstone_dot_core_dot_v1_dot_core__pb2.GetGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
